### ISSUE TITLE
Missing key diffusion

### ISSUE THREAD

**Issue by traveling121** [fdbtrs/IDiff-Face#4]
Traceback (most recent call last):
  File "/data/IDiff-Face-main/sample.py", line 173, in sample
    sampler.run(cfg)
  File "/opt/conda/lib/python3.7/site-packages/lightning_fabric/fabric.py", line 630, in _run_impl
    return run_method(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/lightning_fabric/fabric.py", line 638, in _run_with_setup
    return run_function(*args, **kwargs)
  File "/data/IDiff-Face-main/sample.py", line 28, in run
    diffusion_model = instantiate(train_cfg.diffusion)
omegaconf.errors.ConfigAttributeError: Missing key diffusion
    full_key: diffusion
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Please tell me how to fix this problem?

**Comment by dynasty0** [comment]
@Yolanda2020  hi， I meet the same problem， have you solved the problem?
