### ISSUE TITLE
train_jonas.py is missed where to find it??

### ISSUE THREAD

**Issue by traveling121** [fdbtrs/IDiff-Face#6]
/usr/bin/python3: can't open file 'train_jonas.py': [Errno 2] No such file or directory
/usr/bin/python3: can't open file 'train_jonas.py': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 1218) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_jonas.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-07_09:24:57
  host      : dev-yukun12-yang-globalno1-facr-i1oq-5c9bf969b9-qzhzx
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 1219)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-07_09:24:57
  host      : dev-yukun12-yang-globalno1-facr-i1oq-5c9bf969b9-qzhzx
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 1218)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by fdbtrs** [comment]
the correct file name is train.py. We update shell scriptes
